# Generated by Django 5.0.2 on 2024-05-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Author', models.CharField(max_length=50)),
                ('Is_Publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'books_library',
            },
        ),
    ]
